version: "3"
services:
  app-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=webstore
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - app-db